---
- name: Configure Database servers
  hosts: databases
  become: true

  tasks:
    - name: Install postgresql-server
      ansible.builtin.package:
        name: postgresql-server
        state: present

    # Run postresql-setup command & Start and enable postgresql service & Allow the traffic
    - name: Run postresql-setup command
      ansible.builtin.command: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Start and enable postgresql service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Allow the traffic
      ansible.posix.firewalld:
        port: 5432/tcp
        permanent: true
        state: enabled
        immediate: true
